### ISSUE TITLE
A rudimentary standalone depacking doc?

### ISSUE THREAD

**Issue by silverdr** [bboxy/bitfire#10]
There is the
https://github.com/bboxy/bitfire/blob/master/loader/depacker.asm
depacker code but would it be possible to add a there few lines explaining its standalone usage? Something like "given a block of compressed data located at address $xxxx depacking is done as follows:
- ....
- ...."

It'd help saving lots of analysing time.

**Comment by bboxy** [comment]
Good point, I will add that soonish, i also discovered that some users picked the wrong depacker source and thus failed depacking data.

**Comment by bboxy** [comment]
Added the necessary lines of code to depack a file into the depacker.asm, it should be self-explanatory with ts comments :-)
