### ISSUE TITLE
Bitnax 1.1 SFX doesn't work anymore

### ISSUE THREAD

**Issue by ian-coog** [bboxy/bitfire#12]
Has someone actually tried bitnax --sfx lately? 
It produces non-working prgs. The decompression routine starts with 2 redundant lda/sta pairs, maybe one should be commented, and then the offsets recalculated.

```
		lda .bitnax_decruncher_start,x
		sta .decruncher,x
;!if .bitnax_decruncher_end - .bitnax_decruncher_start > $100 {
		lda .bitnax_decruncher_start + (.bitnax_decruncher_size & $ff),x 
		sta .decruncher + (.bitnax_decruncher_size & $ff),x
;}
		inx
```
I know dali is better but it's also better to provide a working bitnax, or remove it at all =)
The version from bitfire 0.4 (my exe is from february 2016) works

**Comment by bboxy** [comment]
I had added support for compiling the sfx.asm and not using a static byte-array for the depacker. Seems like this fails but also have no motivation to fix for a packer i haven't touch for so long and i have better replacements for, so i better delete it from the repo :-D

**Comment by ian-coog** [comment]
ahah, oh well. case closed =)
