### ISSUE TITLE
"Blocks free" option

### ISSUE THREAD

**Issue by mrdudz** [bboxy/bitfire#4]
An option to alter the number of blocks free would be nice

**Comment by bboxy** [comment]
Possible, but would mess up the BAM and make further file adds difficult. So should be some kind of final manipulaton of the image.

**Comment by bboxy** [comment]
It is added now, it manipulates the blocks free per track in the BAM accordingly, this of course corrupts the BAM to some extent, so it is done as a final step after image is created and all files are placed on it. --free <num> is now another option for d64write.
