### ISSUE TITLE
Option to change blocks of a file entry

### ISSUE THREAD

**Issue by mrdudz** [bboxy/bitfire#5]
Often in a styled directory you want to change the number of blocks for a file, eg 0 blocks for all "seperators", and then "1" block for the boot file "2" blocks for the notefile etc. It would be nice to be able to do this with d64write

**Comment by bboxy** [comment]
That's a good feature request, will be implemented :-)

**Comment by bboxy** [comment]
The dir-art format has changed as to look like a real dir listing, thus also block-sizes for the files are supported \o/
