### ISSUE TITLE
Docs - and specifically over the dir art.

### ISSUE THREAD

**Issue by BacchusFLT** [bboxy/bitfire#6]
The description on specs for dir art is quite vague in the docs. I haven't build the project but my understanding is that this is the format:

It should be a c64 prg file (two start bytes) loading to $0400. All rows have the significant data to the left and the rest can be anything (for clarity, padding with spaces are advised)

First row (header) is the disk name - 16 chars name, one space and then the DiskId.
The following rows are data of 16 in screen code
Data is concluded with a row (footer) that says "664 blocks free" - anything after this is not significant.

This also means that Bitfire only supports 23 lines of DirArt as out of the 25 rows, the first is the header and the last is the footer.

* I would welcome an update of the docs for anyone interested in the function. Please also confirm the assumptions above.

* Is it possible to add a longer directory than fits on a screen? (My assumption is that it's not actually loaded to screen.

**Comment by bboxy** [comment]
> First row (header) is the disk name - 16 chars name, one space and then the DiskId.
> The following rows are data of 16 in screen code

exactly, a footer is not needed as a number of lines to add to the dir is given. You can also add more than 25 lines by just making the bin file provided having more lines. I chose this simple method, as it reflects a good native workflow by drawing on the screen on a real machine and simply saving the screen buffer to disk. Maybe a native dir-editor in 6502 would be a nice addon to bitfire?

This is how things look when saving:
![dir_screen](https://user-images.githubusercontent.com/17510154/95295513-862a9480-0877-11eb-9724-f62da3b08210.png)

And this is how things look when the dirart is applied and the dir of the disk-image is shown:
![dir_result](https://user-images.githubusercontent.com/17510154/95295581-9fcbdc00-0877-11eb-91a7-fa1301834b2e.png)

Any ideas to make this more sophisticated are highly welcome :-)

**Comment by BacchusFLT** [comment]
Kewl - thanks!

I have coded something on PC that allows yuo to extract dirart from an
existing d64.

But just to summarise the format;
Two bytes: $00, $04 (startadress)
Header: 16 bytes diskname, one space, 5 byte DiskId and then 18 bytes
padding of space
Fil item: 16 bytes filename and 24 bytes passing of spaces

/Pontus

Den ons 7 okt. 2020 kl 08:32 skrev bboxy <notifications@github.com>:

**Comment by bboxy** [comment]
Exactly, that is how the format works. The startaddress is technically there from c64-side, the d64write-tool just skips those two bytes, so the address can infact be just any 2 bytes. But $0400 is nice when we look at it as a saved screen :-)

**Comment by BacchusFLT** [comment]
Tool done for extracting dirart from D64s and pasting it in Bitfire format
:-)

To be released in a near future ...

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den mån 19 okt. 2020 kl 10:21 skrev Tobias Bindhammer <
notifications@github.com>:

**Comment by bboxy** [comment]
On the upcoming verson the dirart-format has changed, it now expects the data just as it would be a directory-listing on the screen, an example is added as .bin and .png to the repository
